### ISSUE TITLE
Use distanceSquared over distance for better performance in SegmentSystem

### ISSUE THREAD

**Issue by eviltak** [Terasology/SegmentedPaths#3]
The `segmentMatch` method of the `SegmentSystem` class uses the `distance` method for distance comparision, which can be replaced by `distanceSquared` to avoid a relatively expensive sqrt operation. Since this method is called numerous times in a frame (via the `SegmentSystem.move` method and other external dependers), this may bring about a noticeable improvement in performance for worlds with a sizeable number of `Segment`s.

https://github.com/Terasology/SegmentedPaths/blob/6f5a9856de35cc441028d44dbf041c875aef6fa2/src/main/java/org/terasology/segmentedpaths/controllers/SegmentSystem.java#L202-L209

**Comment by eviltak** [comment]
@jellysnake @pollend I'd like to take this up as a GCI task, after I've cleared a few others :)

**Comment by pollend** [comment]
I really don't think this is that big of an issue. This is only ever is calculated once when a cart crosses a boundary between two segments. The performance saving is basically close to zero.  This doesn't hurt to make the change anyway. I wouldn't really consider this for a task given how trivial this is to fix.
